import fs from 'fs';
import path from 'path';
import chalk from 'chalk';
import { normalizePath } from '../utils/paths';
import { ProcessedImageResult } from './processor';

export const generateConfigTypes = async (
  typesDir: string,
  breakpoints: Record<string, number>
) => {
  const breakpointLines = Object.keys(breakpoints)
    .map((k) => `    '${k}': number;`)
    .join('\n');

  const configTypeContent = `// Auto-generated. Do not edit.
import 'next-granular-images';

declare module 'next-granular-images' {
  export interface GranularBreakpointOverrides {
${breakpointLines}
  }
}
`;
  await fs.promises.mkdir(typesDir, { recursive: true });
  await fs.promises.writeFile(
    path.join(typesDir, 'config.d.ts'),
    configTypeContent
  );
  console.log(chalk.gray('Generated config.d.ts'));
};

export const generateTypeScriptFile = async (
  outputDir: string,
  images: Array<{
    name: string;
    data: ProcessedImageResult;
    relativePath: string;
  }>
) => {
  const sortedImages = [...images].sort((a, b) =>
    a.relativePath.localeCompare(b.relativePath)
  );
  const usedNames = new Map<string, number>();

  sortedImages.forEach((img) => {
    const baseVarName = sanitizeVarName(img.name);
    usedNames.set(baseVarName, (usedNames.get(baseVarName) || 0) + 1);
  });

  const lines = sortedImages.map((img) => {
    const varName = sanitizeVarName(img.name);

    const toPublicUrl = (fullPath: string | undefined) => {
      if (!fullPath) return undefined;
      const normalized = normalizePath(fullPath);
      const publicIndex = normalized.indexOf('/public/');
      if (publicIndex !== -1) {
        return normalized.substring(publicIndex + 7);
      }
      return normalized;
    };

    const buildSrcSetString = (variants: Record<number, string>) => {
      if (!variants || Object.keys(variants).length === 0) return undefined;
      return Object.entries(variants)
        .map(([width, filePath]) => `${toPublicUrl(filePath)} ${width}w`)
        .join(', ');
    };

    const avifSrcSet = buildSrcSetString(img.data.variants.avif);
    const webpSrcSet = buildSrcSetString(img.data.variants.webp);
    const fallbackSrc = toPublicUrl(img.data.variants.original);

    const blurVarName = `${varName}_blur`;

    return `/** Generated from ${img.relativePath} */
export const ${varName} = {
  src: "${fallbackSrc}",
  width: ${img.data.originalWidth},
  height: ${img.data.originalHeight},
  dominantColor: "${img.data.dominantColor || ''}",
  variants: {
    avif: ${avifSrcSet ? `"${avifSrcSet}"` : 'undefined'},
    webp: ${webpSrcSet ? `"${webpSrcSet}"` : 'undefined'},
  }
} as const;

export const ${blurVarName} = "${img.data.blurDataURL || ''}";`;
  });

  const content = `// Auto-generated by next-granular-images
${lines.join('\n\n')}
`;

  await fs.promises.mkdir(outputDir, { recursive: true });
  await fs.promises.writeFile(path.join(outputDir, 'images.gen.ts'), content);
};

const sanitizeVarName = (name: string) => {
  return name.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^[0-9]/, '_$&');
};
