import fs from 'fs';
import path from 'path';
import chalk from 'chalk';
import { ProcessedImageResult } from './processor';
import { buildSrcSet, toPublicUrl } from './urls';

export interface GeneratedImageEntry {
  name: string;
  data: ProcessedImageResult;
  relativePath: string;
}

export interface GenerateTypeScriptOptions {
  /** Absolute path of the Next.js `public` directory. Default: `<cwd>/public`. */
  publicRoot?: string;
}

export const generateConfigTypes = async (
  typesDir: string,
  breakpoints: Record<string, number>
) => {
  const breakpointLines = Object.keys(breakpoints)
    .map((k) => `    '${k}': number;`)
    .join('\n');

  const configTypeContent = `// Auto-generated. Do not edit.
import 'next-granular-images';

declare module 'next-granular-images' {
  export interface GranularBreakpointOverrides {
${breakpointLines}
  }
}
`;
  await fs.promises.mkdir(typesDir, { recursive: true });
  await fs.promises.writeFile(
    path.join(typesDir, 'config.d.ts'),
    configTypeContent
  );
  console.log(chalk.gray('Generated config.d.ts'));
};

export const generateTypeScriptFile = async (
  outputDir: string,
  images: GeneratedImageEntry[],
  options: GenerateTypeScriptOptions = {}
) => {
  const { publicRoot } = options;
  const sortedImages = [...images].sort((a, b) =>
    a.relativePath.localeCompare(b.relativePath)
  );

  const lines = sortedImages.map((img) => {
    const varName = sanitizeVarName(img.name);

    const avifSrcSet = buildSrcSet(img.data.variants.avif, publicRoot);
    const webpSrcSet = buildSrcSet(img.data.variants.webp, publicRoot);
    const fallbackSrc = img.data.variants.original
      ? toPublicUrl(img.data.variants.original, publicRoot)
      : undefined;

    const blurVarName = `${varName}_blur`;

    return `/** Generated from ${img.relativePath} */
export const ${varName} = {
  src: "${fallbackSrc}",
  width: ${img.data.originalWidth},
  height: ${img.data.originalHeight},
  dominantColor: "${img.data.dominantColor || ''}",
  variants: {
    avif: ${avifSrcSet ? `"${avifSrcSet}"` : 'undefined'},
    webp: ${webpSrcSet ? `"${webpSrcSet}"` : 'undefined'},
  }
} as const;

export const ${blurVarName} = "${img.data.blurDataURL || ''}";`;
  });

  const content = `// Auto-generated by next-granular-images
${lines.join('\n\n')}
`;

  await fs.promises.mkdir(outputDir, { recursive: true });
  await fs.promises.writeFile(path.join(outputDir, 'images.gen.ts'), content);
};

/** Turns a file name into a JavaScript identifier. */
export const sanitizeVarName = (name: string): string => {
  return name.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^[0-9]/, '_$&');
};
