import fs from 'fs';
import path from 'path';
import { ProcessedImageResult } from './processor';
import { buildSrcSet, toPublicUrl } from './urls';
import { logger } from '../utils/logger';

export interface GeneratedImageEntry {
  name: string;
  data: ProcessedImageResult;
  relativePath: string;
}

export interface GenerateTypeScriptOptions {
  /** Absolute path of the Next.js `public` directory. Default: `<cwd>/public`. */
  publicRoot?: string;
  /**
   * Configured breakpoints. Emitted once per file and referenced from every
   * image, so the component can use them at runtime for art direction.
   */
  breakpoints?: Record<string, number>;
}

/** Module-private constant holding the breakpoints in each images.gen.ts. */
const BREAKPOINTS_CONST = '__granularBreakpoints';

export const generateConfigTypes = async (
  typesDir: string,
  breakpoints: Record<string, number>
) => {
  const breakpointLines = Object.keys(breakpoints)
    .map((k) => `    ${JSON.stringify(k)}: number;`)
    .join('\n');

  const configTypeContent = `// Auto-generated. Do not edit.
import 'next-granular-images';

declare module 'next-granular-images' {
  export interface GranularBreakpointOverrides {
${breakpointLines}
  }
}
`;
  await fs.promises.mkdir(typesDir, { recursive: true });
  await fs.promises.writeFile(
    path.join(typesDir, 'config.d.ts'),
    configTypeContent
  );
  logger.debug('Generated config.d.ts');
};

export const generateTypeScriptFile = async (
  outputDir: string,
  images: GeneratedImageEntry[],
  options: GenerateTypeScriptOptions = {}
) => {
  const { publicRoot, breakpoints } = options;
  const breakpointsLine = breakpoints ? `\n  breakpoints: ${BREAKPOINTS_CONST},` : '';
  // Plain code-unit order: localeCompare depends on the machine locale, which
  // would make the generated file (and name suffixes) differ between machines.
  const sortedImages = [...images].sort((a, b) =>
    a.relativePath < b.relativePath ? -1 : a.relativePath > b.relativePath ? 1 : 0
  );
  const varNames = assignVarNames(sortedImages.map((img) => img.name));

  const lines = sortedImages.map((img, index) => {
    const varName = varNames[index];

    const avifSrcSet = buildSrcSet(img.data.variants.avif, publicRoot);
    const webpSrcSet = buildSrcSet(img.data.variants.webp, publicRoot);
    const fallbackSrc = img.data.variants.original
      ? toPublicUrl(img.data.variants.original, publicRoot)
      : '';

    return `/** Generated from ${toCommentText(img.relativePath)} */
export const ${varName} = {
  src: ${str(fallbackSrc)},
  width: ${img.data.originalWidth},
  height: ${img.data.originalHeight},
  dominantColor: ${str(img.data.dominantColor || '')},${breakpointsLine}
  variants: {
    avif: ${avifSrcSet ? str(avifSrcSet) : 'undefined'},
    webp: ${webpSrcSet ? str(webpSrcSet) : 'undefined'},
  }
} as const;

export const ${varName}_blur = ${str(img.data.blurDataURL || '')};`;
  });

  const header = breakpoints
    ? `const ${BREAKPOINTS_CONST} = ${JSON.stringify(breakpoints)} as const;\n\n`
    : '';
  const content = `// Auto-generated by next-granular-images
${header}${lines.join('\n\n')}
`;

  await fs.promises.mkdir(outputDir, { recursive: true });
  await fs.promises.writeFile(path.join(outputDir, 'images.gen.ts'), content);
};

/** A double-quoted, fully escaped string literal. */
const str = (value: string) => JSON.stringify(value);

/** Keeps a value from closing the surrounding block comment. */
const toCommentText = (value: string) =>
  value.replace(/\\/g, '/').replace(/\*\//g, '*\\/').replace(/[\r\n]+/g, ' ');

// Reserved words (including strict-mode ones) plus globals that cannot be
// redeclared as module-level constants.
const RESERVED_WORDS = new Set([
  'arguments', 'await', 'break', 'case', 'catch', 'class', 'const', 'continue',
  'debugger', 'default', 'delete', 'do', 'else', 'enum', 'eval', 'export',
  'extends', 'false', 'finally', 'for', 'function', 'if', 'implements', 'import',
  'in', 'instanceof', 'interface', 'let', 'new', 'null', 'package', 'private',
  'protected', 'public', 'return', 'static', 'super', 'switch', 'this', 'throw',
  'true', 'try', 'typeof', 'var', 'void', 'while', 'with', 'yield',
  'undefined', 'NaN', 'Infinity',
]);

/** Turns a file name into a valid, non-reserved JavaScript identifier. */
export const sanitizeVarName = (name: string): string => {
  let id = name.replace(/[^a-zA-Z0-9_]/g, '_');
  if (id === '') id = '_';
  if (/^[0-9]/.test(id)) id = `_${id}`;
  if (RESERVED_WORDS.has(id)) id = `${id}_`;
  return id;
};

/**
 * Picks one identifier per image so that neither `<name>` nor `<name>_blur`
 * collides with another export in the same file (`hero-image` and
 * `hero_image` both sanitize to `hero_image`). Later names get `_2`, `_3`...
 */
export const assignVarNames = (names: string[]): string[] => {
  const used = new Set<string>([BREAKPOINTS_CONST]);
  return names.map((name) => {
    const base = sanitizeVarName(name);
    let candidate = base;
    for (let n = 2; used.has(candidate) || used.has(`${candidate}_blur`); n++) {
      candidate = `${base}_${n}`;
    }
    used.add(candidate);
    used.add(`${candidate}_blur`);
    return candidate;
  });
};

const IMAGES_FILE = 'images.gen.ts';

const findGeneratedFiles = async (dir: string): Promise<string[]> => {
  if (!fs.existsSync(dir)) return [];
  const entries = await fs.promises.readdir(dir, { withFileTypes: true });
  const nested = await Promise.all(
    entries.map((entry) => {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) return findGeneratedFiles(full);
      return entry.name === IMAGES_FILE ? [full] : [];
    })
  );
  return nested.flat();
};

/** Removes now-empty directories between `dir` and `stopAt` (exclusive). */
const removeEmptyParents = async (dir: string, stopAt: string) => {
  let current = dir;
  while (current !== stopAt && current.startsWith(stopAt)) {
    if ((await fs.promises.readdir(current)).length > 0) return;
    await fs.promises.rmdir(current);
    current = path.dirname(current);
  }
};

/**
 * Writes one `images.gen.ts` per source directory and deletes the
 * `images.gen.ts` files left over from directories that no longer have images.
 * Only files named `images.gen.ts` (owned by this tool) are ever removed.
 */
export const writeImageTypes = async (
  typesDir: string,
  imagesByDir: Record<string, GeneratedImageEntry[]>,
  options: GenerateTypeScriptOptions = {}
): Promise<void> => {
  const written = new Set<string>();
  for (const [dir, images] of Object.entries(imagesByDir)) {
    const targetDir = path.join(typesDir, dir);
    await generateTypeScriptFile(targetDir, images, options);
    written.add(path.resolve(targetDir, IMAGES_FILE));
  }

  for (const file of await findGeneratedFiles(typesDir)) {
    if (written.has(path.resolve(file))) continue;
    await fs.promises.rm(file, { force: true });
    logger.debug(`Removed stale ${path.relative(typesDir, file)}`);
    await removeEmptyParents(path.dirname(file), path.resolve(typesDir));
  }
};

/**
 * Deletes every `images.gen.ts` under `typesDir` (plus folders left empty).
 * Returns the files that were (or, with `dryRun`, would be) removed.
 */
export const removeImageTypes = async (
  typesDir: string,
  { dryRun = false }: { dryRun?: boolean } = {}
): Promise<string[]> => {
  const files = await findGeneratedFiles(typesDir);
  if (dryRun) return files;
  for (const file of files) {
    await fs.promises.rm(file, { force: true });
    await removeEmptyParents(path.dirname(file), path.resolve(typesDir));
  }
  return files;
};
